### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jarodium** [caruccio/openshift-gearman-cartridge#1]
Hello you say that

"In order to create your application, first you need to register at Getup Cloud. Go to http://getupcloud.com/#/sign-up and signup for free. You receive a free 750h trial to test our services."

After those 750h will I be able to continue using gearman?

**Comment by caruccio** [comment]
Hi @jarodium.

Please note this platform is being discontinued, so new users can't register anymore. We are in the process of transitioning to OpenShift v3, which will be available mid April.

That said, you can still use this cartridge on [OpenShift Online by RedHat](https://www.openshift.com/) with a little modification: the [gearmand binary](https://github.com/getupcloud/openshift-gearman-cartridge/blob/master/bin/control#L32)  is probably not available there, so you need to fork this repo and ship it with the binary.

RPMs to gearman can be found in [EPEL](https://dl.fedoraproject.org/pub/epel/6/x86_64/) and [SCL](https://www.softwarecollections.org/en/).
